export const data = {
  type_plant: [
    { id: 1, nom: "Plants frais" },
    { id: 2, nom: "Plants frigo" },
    { id: 3, nom: "Plants motte" },
  ],
  pépiniériste: [
    { id: 1, nom: "Pépinières du Sud" },
    { id: 2, nom: "Plants & Co" },
    { id: 3, nom: "Fruitiers Express" },
  ],
  année: [{ id: 2022 }, { id: 2023 }, { id: 2024 }],
  fruit: [
    { id: 1, nom: "Fraise" },
    { id: 2, nom: "Framboise" },
  ],
  type_plantation: [
    { id: 1, nom: "Plein champ" },
    { id: 2, nom: "Sous serre" },
    { id: 3, nom: "Hors-sol" },
  ],
  parcelle: [
    { id: 1, nom: "Parcelle A", surface: 2500.0, type_id: 1 },
    { id: 2, nom: "Parcelle B", surface: 1800.0, type_id: 2 },
    { id: 3, nom: "Parcelle C", surface: 3000.0, type_id: 3 },
  ],
  type_plateau: [
    { id: 1, nom: "Barquette 250g", format: "Petit", poids: 0.25 },
    { id: 2, nom: "Barquette 500g", format: "Moyen", poids: 0.5 },
    { id: 3, nom: "Caisse 2kg", format: "Grand", poids: 2.0 },
  ],
  fournisseur: [
    { id: 1, nom: "FruitSupply" },
    { id: 2, nom: "AgriSource" },
    { id: 3, nom: "BerryBest" },
  ],
  variété: [
    { id: 1, nom: "Gariguette", fruit_id: 1, saisonnalité: "Précoce" },
    { id: 2, nom: "Ciflorette", fruit_id: 1, saisonnalité: "Mi-saison" },
    { id: 3, nom: "Mara des Bois", fruit_id: 1, saisonnalité: "Remontante" },
    { id: 4, nom: "Heritage", fruit_id: 2, saisonnalité: "Remontante" },
    { id: 5, nom: "Tulameen", fruit_id: 2, saisonnalité: "Non-remontante" },
  ],
  plantation: [
    {
      id: 1,
      campagne: 2022,
      etat: "Terminé",
      parcelle_id: 1,
      nombre_plants: 5000,
      variété_id: 1,
      type_plants_id: 1,
      fournisseur_id: 1,
      pépiniériste_id: 1,
      date: "2022-03-15",
      passeport_phyto: "PH2022001",
    },
    {
      id: 2,
      campagne: 2022,
      etat: "Terminé",
      parcelle_id: 2,
      nombre_plants: 3000,
      variété_id: 4,
      type_plants_id: 2,
      fournisseur_id: 2,
      pépiniériste_id: 2,
      date: "2022-04-01",
      passeport_phyto: "PH2022002",
    },
    {
      id: 3,
      campagne: 2023,
      etat: "En cours",
      parcelle_id: 3,
      nombre_plants: 6000,
      variété_id: 2,
      type_plants_id: 3,
      fournisseur_id: 3,
      pépiniériste_id: 3,
      date: "2023-03-20",
      passeport_phyto: "PH2023001",
    },
  ],
  ramassage: [
    {
      id: 1,
      parcelle_id: 1,
      date: "2022-05-15",
      periode_journée: "Matin",
      nombre_plateaux: 100,
      type_plateau_id: 1,
    },
    {
      id: 2,
      parcelle_id: 1,
      date: "2022-05-30",
      periode_journée: "Après-midi",
      nombre_plateaux: 150,
      type_plateau_id: 2,
    },
    {
      id: 3,
      parcelle_id: 2,
      date: "2022-06-10",
      periode_journée: "Matin",
      nombre_plateaux: 80,
      type_plateau_id: 3,
    },
    {
      id: 4,
      parcelle_id: 2,
      date: "2022-06-25",
      periode_journée: "Après-midi",
      nombre_plateaux: 120,
      type_plateau_id: 1,
    },
    {
      id: 5,
      parcelle_id: 3,
      date: "2022-07-05",
      periode_journée: "Matin",
      nombre_plateaux: 200,
      type_plateau_id: 2,
    },
    {
      id: 6,
      parcelle_id: 3,
      date: "2022-07-20",
      periode_journée: "Après-midi",
      nombre_plateaux: 180,
      type_plateau_id: 3,
    },
    {
      id: 7,
      parcelle_id: 1,
      date: "2022-08-01",
      periode_journée: "Matin",
      nombre_plateaux: 90,
      type_plateau_id: 1,
    },
    {
      id: 8,
      parcelle_id: 2,
      date: "2022-08-15",
      periode_journée: "Après-midi",
      nombre_plateaux: 110,
      type_plateau_id: 2,
    },
    {
      id: 9,
      parcelle_id: 3,
      date: "2022-08-30",
      periode_journée: "Matin",
      nombre_plateaux: 160,
      type_plateau_id: 3,
    },
    {
      id: 10,
      parcelle_id: 1,
      date: "2022-09-10",
      periode_journée: "Après-midi",
      nombre_plateaux: 130,
      type_plateau_id: 1,
    },
    {
      id: 11,
      parcelle_id: 1,
      date: "2023-05-10",
      periode_journée: "Matin",
      nombre_plateaux: 110,
      type_plateau_id: 1,
    },
    {
      id: 12,
      parcelle_id: 1,
      date: "2023-05-25",
      periode_journée: "Après-midi",
      nombre_plateaux: 160,
      type_plateau_id: 2,
    },
    {
      id: 13,
      parcelle_id: 2,
      date: "2023-06-05",
      periode_journée: "Matin",
      nombre_plateaux: 90,
      type_plateau_id: 3,
    },
    {
      id: 14,
      parcelle_id: 2,
      date: "2023-06-20",
      periode_journée: "Après-midi",
      nombre_plateaux: 130,
      type_plateau_id: 1,
    },
    {
      id: 15,
      parcelle_id: 3,
      date: "2023-07-01",
      periode_journée: "Matin",
      nombre_plateaux: 210,
      type_plateau_id: 2,
    },
    {
      id: 16,
      parcelle_id: 3,
      date: "2023-07-15",
      periode_journée: "Après-midi",
      nombre_plateaux: 190,
      type_plateau_id: 3,
    },
    {
      id: 17,
      parcelle_id: 1,
      date: "2023-07-30",
      periode_journée: "Matin",
      nombre_plateaux: 100,
      type_plateau_id: 1,
    },
    {
      id: 18,
      parcelle_id: 2,
      date: "2023-08-10",
      periode_journée: "Après-midi",
      nombre_plateaux: 120,
      type_plateau_id: 2,
    },
    {
      id: 19,
      parcelle_id: 3,
      date: "2023-08-25",
      periode_journée: "Matin",
      nombre_plateaux: 170,
      type_plateau_id: 3,
    },
    {
      id: 20,
      parcelle_id: 1,
      date: "2023-09-05",
      periode_journée: "Après-midi",
      nombre_plateaux: 140,
      type_plateau_id: 1,
    },
    {
      id: 21,
      parcelle_id: 1,
      date: "2024-05-05",
      periode_journée: "Matin",
      nombre_plateaux: 120,
      type_plateau_id: 1,
    },
    {
      id: 22,
      parcelle_id: 1,
      date: "2024-05-20",
      periode_journée: "Après-midi",
      nombre_plateaux: 170,
      type_plateau_id: 2,
    },
    {
      id: 23,
      parcelle_id: 2,
      date: "2024-06-01",
      periode_journée: "Matin",
      nombre_plateaux: 100,
      type_plateau_id: 3,
    },
    {
      id: 24,
      parcelle_id: 2,
      date: "2024-06-15",
      periode_journée: "Après-midi",
      nombre_plateaux: 140,
      type_plateau_id: 1,
    },
    {
      id: 25,
      parcelle_id: 3,
      date: "2024-06-30",
      periode_journée: "Matin",
      nombre_plateaux: 220,
      type_plateau_id: 2,
    },
    {
      id: 26,
      parcelle_id: 3,
      date: "2024-07-10",
      periode_journée: "Après-midi",
      nombre_plateaux: 200,
      type_plateau_id: 3,
    },
    {
      id: 27,
      parcelle_id: 1,
      date: "2024-07-25",
      periode_journée: "Matin",
      nombre_plateaux: 110,
      type_plateau_id: 1,
    },
    {
      id: 28,
      parcelle_id: 2,
      date: "2024-08-05",
      periode_journée: "Après-midi",
      nombre_plateaux: 130,
      type_plateau_id: 2,
    },
    {
      id: 29,
      parcelle_id: 3,
      date: "2024-08-20",
      periode_journée: "Matin",
      nombre_plateaux: 180,
      type_plateau_id: 3,
    },
    {
      id: 30,
      parcelle_id: 1,
      date: "2024-09-01",
      periode_journée: "Après-midi",
      nombre_plateaux: 150,
      type_plateau_id: 1,
    },
  ],
};
